### PR TITLE
refine the simplified characters

### PR DESCRIPTION
**Pull request by yuanzhouIR**

### CODE REVIEW

**Comment by chainsawriot** [comment]
Thanks for the PR, @yuanzhouIR.

I agree with the additions of 它 and modify the word 著/着. I will add them also to the traditional Chinese wordlist.

I would suggest adding 那么 but keeping 那末 because both are used but with different grammatical meanings. I think 那末 may have been merged 那么 in more recent Chinese in mainland China, but in some writings by Mao, for example, he made distinctions between the two terms.

**Review by chainsawriot — CHANGES_REQUESTED** [review]
Thanks for the PR, @yuanzhouIR.

I agree with the additions of 它 and modify the word 著/着. I will add them also to the traditional Chinese wordlist.

I would suggest adding 那么 but keeping 那末 because both are used but with different grammatical meanings. I think 那末 may have been merged 那么 in more recent Chinese in mainland China, but in some writings by Mao, for example, he made distinctions between the two terms.

**Comment by yuanzhouIR** [comment]
@chainsawriot Yes. 那末 is used by the Mao generation but deprecated in rencent Chinese. We can keep both just in case.

Also, I think some words in the list would never be used in Mandarin, such as 哪时, 或能, 远是, and so forth. We can remove those words to make our list more concise. Moreover, phrases like 把我, 对我, 我自己 would be tokenized as "把""我", "对""我", "我""自己" in text preprocessing. I don't think any effective tokenization tool will keep them as one token. Maybe we should remove those phrases and just add 把, 对, 让, and other causatives.

**Comment by chainsawriot** [comment]
@yuanzhouIR Thanks for your suggestions. There are at least two issues here.

I think it is better to be broad. Please remember that simplified Chinese is not THE written language of Mandarin Chinese in mainland China. It also used as a written language in Singapore, Malaysia, and diaspora communities too. They use the language quite differently to the standard Mandarin Chinese. Remember, be broad, but yet don't introduce ambiguity.

Take the example 那末 again. Simplified Chinese news articles of Deutsche Welle (DW) and BBC still make a distinction between 那末 and 那么. Keeping both would not introduce ambiguity, so I suggest to keep both. I think it is better to **add terms used in China, instead of remove terms because they are not used in China**. Once again, be broad.

Regarding the issue of 把我, you are right that a reasonable tokenizer would token 把我 into 把 and 我. I have done a study on a reasonably large corpus of (traditional) Chinese text and these stopwords are not used.

https://github.com/chainsawriot/marimo_test/blob/master/testing.md

I keep words like 把我 there for compatibility purposes (with the other languages that have accusative / dative pronounces, e.g. me in English or mich/mir in German) and in general, these words would not introduce ambiguity. Also, `quanteda::tokens` is capable of tokenizing sentences into bigrams and thus 把我 (or 把_我) will be considered as a stopword.

I would keep the issue of adding new categories of stopwords (e.g. 把) to @koheiw .

Once again, thank you for the PR and the suggestions.

**Comment by yuanzhouIR** [comment]
@chainsawriot Thank you for your reminder.

If words like 哪时, 或能, 远是 are used by people outside mainland China, it is reasonable to keep those words.

As your experiment shows, phrases like 把我, 对我, 我自己 did not come out as single tokens. We can keep them for compatibility purpose as you said. However, I don't think it means a lot. This is because when we do n-gram analysis, we usually do not remove stopwords or we first remove the stopwords and then compound.

**Review by chainsawriot — APPROVED** [review]
I think it would be faster for us to merge this first and then I submit a subsequent edit.

**Pull request merged**
