### PR TITLE
Chinese stopwords

### PR DESCRIPTION
**Pull request by chainsawriot**
Added both traditional and simplified Chinese stopwords.

### CODE REVIEW

**Comment by koheiw** [comment]
Chinese stopwords lists would a great addition. Could you check if the words in your list match how texts are segmented by `tokens()`? This is a difficult problem in Chinese and Japanese, but I want to know how good it is.

**Comment by chainsawriot** [comment]
@koheiw I have a large-ish corpus of Traditional Chinese press releases from the government and I have used that as the "benchmark" of the Traditional Chinese wordlist with `quanteda::tokens`. 

https://github.com/chainsawriot/marimo_test/blob/master/testing.md

And yes, there were actually some missing permutations of stopwords. I have added them back to the wordlist (da13913). I can't see any missing but frequently used stopwords anymore.

However, there are missing categories of stopwords that are not available in the master English wordlist, e.g. interjection, tense markers (e.g. Chinese's 了, which functions similarly to the Japanese りょう   in しゅうりょう ), ordinal numbers (e.g. 第一) etc. Some modal verbs are missing too, e.g. can. Probably because 'can' has multiple meanings (e.g. soda can) in English.

**Comment by koheiw** [comment]
Our stopwords lists should remove grammatical words from our corpora but we still do not want to overfit that to them. Collecting frequent words from our corpora leads overfitting, so I created a simple tool that help us to find similar grammatical words independent of their frequencies using FCM. This worked fairly well in English and Japanese at least. Can you try?

```r
get_equivalent <- function(x, seeds) {
    stopifnot(is.fcm(x))
    y <- dfm_select(x, seeds)
    x <- dfm_remove(x, seeds)
    temp <- proxyC::simil(x, y, margin = 2)
    sort(apply(temp, 1, max), decreasing = TRUE)
}

corp_en <- readRDS("data_corpus_sent_en.RDS") # documents are sentences
toks_en <- tokens(corp_en, remove_punct = TRUE) %>% 
    tokens_tolower()
fcmt_en <- fcm(toks_en, "window", window = 1, tri = FALSE, ordered = TRUE)

# pronouns
head(get_equivalent(fcmt_en, c("i", "we", "you", "they", "he", "she")), 30)

# interogative
head(get_equivalent(fcmt_en, c("how", "why", "what", "when")), 30)
```
The output on my corpus.
```
> # pronouns
> head(get_equivalent(fcmt_en, c("i", "we", "you", "they", "he", "she")), 30)
         we're            i'm             it          we've           he's        they've         you've         you're        they're 
     0.9527152      0.9463197      0.9287174      0.9207284      0.9180698      0.9147448      0.9129459      0.9118565      0.9055780 
          i've          there        there's          she's           he'd         you'll           it's         nobody          we'll 
     0.8975871      0.8926369      0.8731639      0.8724412      0.8687101      0.8665326      0.8648489      0.8598228      0.8438604 
          i'll          she'd      asquith's            i'd          you'd         that's non-registered       although         no-one 
     0.8411236      0.8306789      0.8272991      0.8237820      0.8205318      0.8161253      0.8115739      0.8105593      0.8062537 
       bumpily      post-1974    above-board 
     0.8032053      0.8032053      0.8032053 
> # interogative
> head(get_equivalent(fcmt_en, c("how", "why", "what", "when")), 30)
      what's   protecting          our establishing   destroying           my      china's          his     stopping          its 
   0.8710543    0.8497028    0.8433727    0.8396685    0.8366265    0.8342010    0.8339278    0.8303350    0.8267935    0.8238600 
       their    restoring         your          the          her     creating      whether      forming   delivering   preventing 
   0.8231307    0.8194102    0.8185353    0.8172517    0.8172157    0.8101985    0.8097885    0.8073364    0.8066775    0.8058495 
   improving     moscow's     europe's      finding  influencing     bringing     russia's washington's       saving    extending 
   0.8041444    0.7990894    0.7990082    0.7986709    0.7985227    0.7976185    0.7971225    0.7966479    0.7958860    0.7946782
```

**Comment by koheiw** [comment]
Let's discuss what category our stopwords lists should have in a separate issue, because we need coordinate across languages. 

However, I think it is fine to add a tense marker category here, because other languages may not need it. Japanese tense maker for the past is "た" (I did not include this in the list because we can remove it using regex).

**Comment by chainsawriot** [comment]
I've indeed tried your method. It could somehow work, but not very effectively.

I have modified your method a little bit. The idea is very much the same. Basically, I trained a set of GloVe word-embeddings and then used it to identify tokens that function grammatically similar to other stopwords. It works better for my Chinese corpus.

https://github.com/chainsawriot/marimo_test/blob/master/get_equi.md

So, there are still some stopword-like words that do not have the equivalent categories in the English master list.

e.g. Ordinal, common phrases such as: in fact (其實), such as (包括), also (都是).

But for stopwords that have equivalent categories, I think I have pretty much added all of them (dd2d59c).

**Comment by koheiw** [comment]
Nice. I am sure that word-embeddings perform better in the task.

**Comment by koheiw** [comment]
Let's make small adjustment later. Thanks @chainsawriot.

**Pull request merged**
